services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - .env
    ports:
      - "${HOST_PORT}:${DB_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shared-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
    expose:
      - "80"
    networks:
      - shared-network

volumes:
  mysql_data:

networks:
  shared-network:
    name: devops-shared-network
    external: true