services:
  mysql:
    image: ${MYSQL_IMAGE}
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${HOST_PORT}:${DB_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shared-network

  phpmyadmin:
    image: ${PHPMYADMIN_IMAGE}
    container_name: ${PHPMYADMIN_CONTAINER_NAME}
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
    expose:
      - "80"
    networks:
      - shared-network

  mongodb:
    image: ${MONGO_IMAGE}
    container_name: ${MONGO_CONTAINER_NAME}
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "${MONGO_HOST_PORT}:${MONGO_DB_PORT}"

    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

    networks:
      - shared-network

  mongo-express:
    image: ${MONGO_EXPRESS_IMAGE}
    container_name: ${MONGO_EXPRESS_CONTAINER_NAME}
    restart: unless-stopped

    depends_on:
      - mongodb

    env_file:
      - .env

    ports:
      - "${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_CONTAINER_PORT}"

    networks:
      - shared-network

volumes:
  mysql_data:
  mongo-data:
  mongo-config:

networks:
  shared-network:
    name: devops-shared-network
    external: true